name: bb_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0-296.3.beta

# Add regular dependencies here.
dependencies:
  collection: any
  intl: any

  diacritic: any
  image: any
  stack_trace: any


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
